// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scriptorium.Infrastructure.Data;

#nullable disable

namespace Scriptorium.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ScriptoriumDbContext))]
    partial class ScriptoriumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Scriptorium.Domain.Entities.DailyDevotional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiturgicalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyDevotionals");
                });

            modelBuilder.Entity("Scriptorium.Domain.Entities.Homily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyDevotionalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("HomilyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoTraduzido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TranslationAttempts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyDevotionalId")
                        .IsUnique();

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("Homilies");
                });

            modelBuilder.Entity("Scriptorium.Domain.Entities.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyDevotionalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyDevotionalId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("Scriptorium.Domain.Entities.SaintOfTheDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyDevotionalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyDevotionalId")
                        .IsUnique();

                    b.ToTable("Saints");
                });

            modelBuilder.Entity("Scriptorium.Domain.Entities.Homily", b =>
                {
                    b.HasOne("Scriptorium.Domain.Entities.DailyDevotional", "DailyDevotional")
                        .WithOne("Homily")
                        .HasForeignKey("Scriptorium.Domain.Entities.Homily", "DailyDevotionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DailyDevotional");
                });

            modelBuilder.Entity("Scriptorium.Domain.Entities.Reading", b =>
                {
                    b.HasOne("Scriptorium.Domain.Entities.DailyDevotional", "DailyDevotional")
                        .WithMany("Readings")
                        .HasForeignKey("DailyDevotionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyDevotional");
                });

            modelBuilder.Entity("Scriptorium.Domain.Entities.SaintOfTheDay", b =>
                {
                    b.HasOne("Scriptorium.Domain.Entities.DailyDevotional", "DailyDevotional")
                        .WithOne("Saint")
                        .HasForeignKey("Scriptorium.Domain.Entities.SaintOfTheDay", "DailyDevotionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyDevotional");
                });

            modelBuilder.Entity("Scriptorium.Domain.Entities.DailyDevotional", b =>
                {
                    b.Navigation("Homily");

                    b.Navigation("Readings");

                    b.Navigation("Saint");
                });
#pragma warning restore 612, 618
        }
    }
}
